import { Document, Page, View, Text, Image } from "@react-pdf/renderer";
import { pdfStyles as s } from "./styles";
import { fmt, money } from "@/lib/format";
import { LOGO_BUFFER, LOGO_ASPECT } from "./logo";

const LOGO_HEIGHT = 30;

export type DnPdfLine = { name: string; qty: number; unitLabel: string | null; price: number; amount: number };

export type DnPdfData = {
  number: string;
  docType: "DN" | "PRO";
  deliveryDate: string;
  customerName: string;
  customerEmail?: string | null;
  customerPhone?: string | null;
  branchName: string;
  lines: DnPdfLine[];
  total: number;
};

export function DeliveryNotePdf({ dn }: { dn: DnPdfData }) {
  const title = dn.docType === "PRO" ? "PRO FORMA INVOICE" : "DELIVERY NOTE";
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <View style={s.headerRow}>
          <View>
            <Image src={LOGO_BUFFER} style={{ height: LOGO_HEIGHT, width: LOGO_HEIGHT * LOGO_ASPECT }} />
            <Text style={s.brandSub}>Cost Control ERP</Text>
          </View>
          <View>
            <Text style={s.docTitle}>{title}</Text>
            <Text style={s.docNumber}>{dn.number}</Text>
            <Text style={s.docMeta}>Date: {dn.deliveryDate}</Text>
          </View>
        </View>

        <View style={s.metaRow}>
          <View style={s.metaCol}>
            <Text style={s.metaLabel}>Customer</Text>
            <Text style={s.metaName}>{dn.customerName}</Text>
            {dn.customerPhone && <Text style={s.metaLine}>Tel: {dn.customerPhone}</Text>}
            {dn.customerEmail && <Text style={s.metaLine}>{dn.customerEmail}</Text>}
          </View>
          <View style={s.metaCol}>
            <Text style={s.metaLabel}>From</Text>
            <Text style={s.metaName}>{dn.branchName}</Text>
          </View>
        </View>

        <View style={s.table}>
          <View style={s.tHeadRow}>
            <Text style={[s.th, s.colNo]}>#</Text>
            <Text style={[s.th, s.colDesc, { width: "40%" }]}>Description</Text>
            <Text style={[s.th, s.colQty]}>Qty</Text>
            <Text style={[s.th, s.colUnit]}>Unit</Text>
            <Text style={[s.th, s.colAmount]}>Amount</Text>
          </View>
          {dn.lines.map((l, i) => (
            <View style={s.tRow} key={i}>
              <Text style={[s.td, s.colNo]}>{i + 1}</Text>
              <Text style={[s.td, s.colDesc, { width: "40%" }]}>{l.name}</Text>
              <Text style={[s.td, s.colQty]}>{fmt(l.qty, 2)}</Text>
              <Text style={[s.td, s.colUnit]}>{l.unitLabel ?? "-"}</Text>
              <Text style={[s.td, s.colAmount]}>{fmt(l.amount, 2)}</Text>
            </View>
          ))}
        </View>

        <View style={s.totalsBlock}>
          <View style={s.totalsRowFinal}>
            <Text style={s.totalsLabelFinal}>Total</Text>
            <Text style={s.totalsValueFinal}>{money(dn.total, 2)}</Text>
          </View>
        </View>

        <Text style={s.footerNote}>Generated by NAMA YOSO Cost Control ERP.</Text>
      </Page>
    </Document>
  );
}
