import { Document, Page, View, Text, Image } from "@react-pdf/renderer";
import { pdfStyles as s } from "./styles";
import { fmt, money } from "@/lib/format";
import { LOGO_BUFFER, LOGO_ASPECT } from "./logo";

const LOGO_HEIGHT = 30;

export type PoPdfLine = { name: string; qty: number; unitLabel: string | null; rate: number; taxRate: number };

export type PoPdfData = {
  poNumber: string;
  createdDate: string;
  status: string;
  supplierName: string;
  supplierContactName?: string | null;
  supplierPhone?: string | null;
  supplierEmail?: string | null;
  supplierTrn?: string | null;
  supplierPaymentTerms?: string | null;
  deliverToLabel: string;
  notes?: string | null;
  lines: PoPdfLine[];
  net: number;
  vat: number;
  total: number;
};

export function PurchaseOrderPdf({ po }: { po: PoPdfData }) {
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <View style={s.headerRow}>
          <View>
            <Image src={LOGO_BUFFER} style={{ height: LOGO_HEIGHT, width: LOGO_HEIGHT * LOGO_ASPECT }} />
            <Text style={s.brandSub}>Inventory Management</Text>
          </View>
          <View>
            <Text style={s.docTitle}>LOCAL PURCHASE ORDER</Text>
            <Text style={s.docNumber}>{po.poNumber}</Text>
            <Text style={s.docMeta}>Date: {po.createdDate}</Text>
          </View>
        </View>

        <View style={s.metaRow}>
          <View style={s.metaCol}>
            <Text style={s.metaLabel}>Supplier</Text>
            <Text style={s.metaName}>{po.supplierName}</Text>
            {po.supplierContactName && <Text style={s.metaLine}>Attn: {po.supplierContactName}</Text>}
            {po.supplierPhone && <Text style={s.metaLine}>Tel: {po.supplierPhone}</Text>}
            {po.supplierEmail && <Text style={s.metaLine}>{po.supplierEmail}</Text>}
            {po.supplierTrn && <Text style={s.metaLine}>TRN: {po.supplierTrn}</Text>}
          </View>
          <View style={s.metaCol}>
            <Text style={s.metaLabel}>Deliver To</Text>
            <Text style={s.metaName}>{po.deliverToLabel}</Text>
            {po.supplierPaymentTerms && <Text style={s.metaLine}>Payment Terms: {po.supplierPaymentTerms}</Text>}
            <Text style={[s.metaLine, { marginTop: 6 }]}>Status: {po.status}</Text>
          </View>
        </View>

        <View style={s.table}>
          <View style={s.tHeadRow}>
            <Text style={[s.th, s.colNo]}>#</Text>
            <Text style={[s.th, s.colDesc]}>Description</Text>
            <Text style={[s.th, s.colQty]}>Qty</Text>
            <Text style={[s.th, s.colUnit]}>Unit</Text>
            <Text style={[s.th, s.colRate]}>Rate</Text>
            <Text style={[s.th, s.colAmount]}>Total</Text>
          </View>
          {po.lines.map((l, i) => {
            const taxableAmount = l.qty * l.rate;
            const taxAmount = taxableAmount * (l.taxRate / 100);
            return (
              <View style={s.tRow} key={i}>
                <Text style={[s.td, s.colNo]}>{i + 1}</Text>
                <Text style={[s.td, s.colDesc]}>{l.name}</Text>
                <Text style={[s.td, s.colQty]}>{fmt(l.qty, 2)}</Text>
                <Text style={[s.td, s.colUnit]}>{l.unitLabel ?? "-"}</Text>
                <Text style={[s.td, s.colRate]}>{fmt(l.rate, 2)}</Text>
                <Text style={[s.td, s.colAmount]}>{fmt(taxableAmount + taxAmount, 2)}</Text>
              </View>
            );
          })}
        </View>

        <View style={s.totalsBlock}>
          <View style={s.totalsRow}>
            <Text style={s.totalsLabel}>Subtotal</Text>
            <Text style={s.totalsValue}>{fmt(po.net, 2)}</Text>
          </View>
          <View style={s.totalsRow}>
            <Text style={s.totalsLabel}>Tax Amount</Text>
            <Text style={s.totalsValue}>{fmt(po.vat, 2)}</Text>
          </View>
          <View style={s.totalsRowFinal}>
            <Text style={s.totalsLabelFinal}>Total</Text>
            <Text style={s.totalsValueFinal}>{money(po.total, 2)}</Text>
          </View>
        </View>

        {po.notes && (
          <View>
            <Text style={s.metaLabel}>Notes</Text>
            <Text style={s.metaLine}>{po.notes}</Text>
          </View>
        )}

        <Text style={s.footerNote}>Generated by NAMA YOSO Inventory Management.</Text>
      </Page>
    </Document>
  );
}
