import { StyleSheet } from "@react-pdf/renderer";

export const pdfStyles = StyleSheet.create({
  page: { padding: 36, fontSize: 10, fontFamily: "Helvetica", color: "#111" },
  headerRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", borderBottomWidth: 2, borderBottomColor: "#111", paddingBottom: 12, marginBottom: 16 },
  brand: { fontSize: 14, fontWeight: 700 },
  brandSub: { fontSize: 8, color: "#666", marginTop: 2 },
  docTitle: { fontSize: 14, fontWeight: 700, letterSpacing: 1, textAlign: "right" },
  docNumber: { fontSize: 11, fontWeight: 700, marginTop: 2, textAlign: "right" },
  docMeta: { fontSize: 9, color: "#666", textAlign: "right" },
  metaRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 18 },
  metaCol: { width: "48%" },
  metaLabel: { fontSize: 8, textTransform: "uppercase", letterSpacing: 1, color: "#888", marginBottom: 3 },
  metaName: { fontSize: 10.5, fontWeight: 700 },
  metaLine: { fontSize: 9.5, marginTop: 1 },
  table: { marginBottom: 14 },
  tHeadRow: { flexDirection: "row", borderBottomWidth: 1.5, borderBottomColor: "#111", paddingBottom: 4, marginBottom: 4 },
  tRow: { flexDirection: "row", borderBottomWidth: 0.5, borderBottomColor: "#e0e0e0", paddingVertical: 4 },
  th: { fontSize: 8.5, fontWeight: 700, textTransform: "uppercase" },
  td: { fontSize: 9.5 },
  colNo: { width: "6%" },
  colDesc: { width: "34%" },
  colQty: { width: "12%", textAlign: "right" },
  colUnit: { width: "12%" },
  colRate: { width: "12%", textAlign: "right" },
  colAmount: { width: "24%", textAlign: "right" },
  totalsBlock: { alignItems: "flex-end", marginBottom: 20 },
  totalsRow: { flexDirection: "row", width: 200, justifyContent: "space-between", paddingVertical: 2 },
  totalsRowFinal: { flexDirection: "row", width: 200, justifyContent: "space-between", paddingTop: 5, marginTop: 3, borderTopWidth: 1.5, borderTopColor: "#111" },
  totalsLabel: { fontSize: 9.5 },
  totalsLabelFinal: { fontSize: 10.5, fontWeight: 700 },
  totalsValue: { fontSize: 9.5 },
  totalsValueFinal: { fontSize: 10.5, fontWeight: 700 },
  footerNote: { fontSize: 8, color: "#999", marginTop: 24 },
});
